org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# -- Versions --
# Minecraft
minecraft_version=1.20.1
enabled_platforms=fabric,forge

forge_version=47.3.3

fabric_loader_version=0.17.2
fabric_api_version=0.92.2+1.20.1

mixin_extras_version=0.3.5

# Registrate
registrate_forge_version=MC1.20-1.3.3
registrate_fabric_version=1.3.79-MC1.20.1

# Theatrical and Extra Lights
theatrical_version=1.0.0-alpha.28.120+mc1.20.1
theatrical_forge_version_range=[1.0.0-alpha.28,)
theatrical_fabric_version_range=>=1.0.0-alpha.28

extra_lights_forge_version=snAwDOU5
extra_lights_fabric_version=oRU7tFgO

arch_api_version=9.1.12

# JEI
jei_version = 15.20.0.112

# Mappings
parchment_version=2023.09.03

# Development QOL
modmenu_version = 7.2.2
lazydfu_version = 0.1.3

# -- Mod Settings --
mod_id=theatricalwb
mod_version=0.0.1
mod_group_id=purplecreate.theatricalwb

# CI
modrinth_id=gYYjwNbc
curseforge_id=1424588
github_repo=PurpleCreate/TheatricalWB
github_branch=main
